# Generated by Django 2.2.7 on 2019-11-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('min_headroom', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRecurringPaymentsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('amount', models.FloatField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_recurring_out', to='accounts.Account')),
            ],
        ),
    ]
