# Generated by Django 2.2.7 on 2019-11-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuretransactions',
            name='annual_date',
            field=models.DateField(default='2013-01-29'),
        ),
    ]
