# Generated by Django 2.2.7 on 2019-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_balance_update',
            field=models.DateField(null=True),
        ),
    ]
