# Generated by Django 2.2.7 on 2019-11-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='current', max_length=50),
        ),
    ]
