# Generated by Django 2.2.7 on 2019-11-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191115_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuretransactions',
            name='annual_date',
            field=models.DateField(null=True),
        ),
    ]
