# Generated by Django 2.2.7 on 2019-11-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_weeklyrecurringout'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecurringout',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecurringout',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='weeklyrecurringout',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
