# Generated by Django 2.2.7 on 2019-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191116_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_balance_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futuretransactions',
            name='annual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futuretransactions',
            name='one_off_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
