# Generated by Django 2.2.7 on 2019-11-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecurringpaymentsout',
            name='day_of_week',
            field=models.DateField(null=True),
        ),
    ]
