# Generated by Django 2.2.7 on 2019-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191114_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrecurringpaymentsout',
            name='day_of_week',
            field=models.CharField(blank=True, default='hello world', max_length=50),
        ),
    ]
